language: c

env:
  global:
    - "HOST_IP=$(/sbin/ifconfig venet0:0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')"
    - DOCKER_HOST=tcp://$HOST_IP:2375
    - DOCKER_PORT_RANGE=2400:2500
    - SLIRP_PORTS=$(seq 2375 2500)

install:
  - sudo apt-get -qqy update
  - wget -qO- https://get.docker.com/ | sh
  - sudo sudo usermod -aG docker "$USER"
  - sudo apt-get -qqy install slirp
  - git clone git://github.com/jpetazzo/sekexe

before_script:
  - "sekexe/run 'mount -t tmpfs -o size=8g tmpfs /var/lib/docker && docker -d -H tcp://0.0.0.0:2375' &"
  - "while ! docker info &> /dev/null ; do sleep 1; done"

script:
  - docker version
  - docker pull vladgh/puppetserver
