version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/standby.sh
      timeout: 300
    - location: scripts/prepare.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
    - location: scripts/standby.sh
      timeout: 300
